#!/bin/bash
echo "Applying theme"
# GTK
gsettings set org.gnome.desktop.interface gtk-theme "vimix-dark-beryl"
# Icons
gsettings set org.gnome.desktop.interface icon-theme "Marwaita-Dark"
# Cursor
gsettings set org.gnome.desktop.interface cursor-theme 'Marwaita'
# Wallpaper
gsettings set org.gnome.desktop.background picture-uri "file:///$HOME/Pictures/UwUntu-Wallpapers/Wall16.jpg"
read -p "Press enter to continue"
